<a href="https://colab.research.google.com/github/MinwooKim1990/TF/blob/main/TFCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sensorflow==2

tf.__version__

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


'2.8.2'

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# utils
def display_some_examples(examples, labels):
  plt.figure(figsize=(10,10)) # figure size
  for i in range(25):
    idx=np.random.randint(0, examples.shape[0]-1) # set random index number from 0 to 5999
    img=examples[idx] 
    label=labels[idx]

    plt.subplot(5,5, i+1) # make subplot size 5,5 only one chanel
    plt.title(str(label)) # set the title with strings
    plt.tight_layout() # set the figure layout for organize
    plt.imshow(img,cmap='gray') # set the image colour as gray not RGB
  plt.show()

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, Input, Dense, MaxPool2D, BatchNormalization, Flatten, GlobalAvgPool2D
import matplotlib.pyplot as plt
import numpy as np

# tensorflow.keras.Sequential
seq_model=tf.keras.Sequential(
    [
     Input(shape=(28,28,1)), # input shape of image data gray scale
     Conv2D(32,(3,3),activation='relu'), #32 filter, 3,3 weight filter I can change for imporove accuracy
     Conv2D(64,(3,3),activation='relu'), # expect 4D tensor
     MaxPool2D(),
     BatchNormalization(), # normalization of input minimize cost function normalize the batch

     Conv2D(128,(3,3), activation='relu'),
     MaxPool2D(),
     BatchNormalization(),

      GlobalAvgPool2D(), # average the value
     Dense(64, activation='relu'),
     Dense(10, activation='softmax') # output layer of NN 10 classes it has to be 10 because of classification result
    ]
)

if __name__=='__main__': 
#if I run my script then I want this part here to be rand and 
#if I import it for example I can import my file into another script and tin that case this part will not be called.
#It is a good habit always add this one on my script when I want to separate the behaviors between importing those scripts and running those scripts
  #pass
  (x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data() # import MNIST dataset from keras
  print('x_train.shape=',x_train.shape)
  print('y_train.shape=',y_train.shape)
  print('x_test.shape=',x_test.shape)
  print('y_test.shape=',y_test.shape)
  
  if False:
    display_some_examples(x_train,y_train) # shouw the sample images
  x_train = x_train.astype('float32')/255 # normalisation for not absolutly 0
  x_test = x_test.astype('float32')/255 

  x_train = np.expand_dims(x_train, axis=-1)
  x_test = np.expand_dims(x_test, axis=-1)

  # if we use categorical_crossentropy, we need to use one hot coding
  # label : 2
  # one hot encoding : [0,0,1,0,0,0,0,0,0,0]
  y_train = tf.keras.utils.to_categorical(y_train, 10)
  y_test = tf.keras.utils.to_categorical(y_test, 10)

  model = seq_model
  #model = functional_model()
  #model = MyCustomModel()
  model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics='accuracy')

  #model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics='accuracy') # important properties
  
  # model training
  model.fit(x_train, y_train, batch_size=64, epochs=5, validation_split=0.1) # batch size is set the number of imagies to check epoch is trials of whole model

  # train, validation( end of every epoch check not use for train ), test 

  # evaluation on test set
  model.evaluate(x_test, y_test, batch_size=64)

  # Saving bestmodel model


x_train.shape= (60000, 28, 28)
y_train.shape= (60000,)
x_test.shape= (10000, 28, 28)
y_test.shape= (10000,)
Epoch 1/5
844/844 [==============================] - 6s 7ms/step - loss: 0.2131 - accuracy: 0.9422 - val_loss: 0.0771 - val_accuracy: 0.9790
Epoch 2/5
844/844 [==============================] - 5s 7ms/step - loss: 0.0515 - accuracy: 0.9838 - val_loss: 0.0510 - val_accuracy: 0.9858
Epoch 3/5
844/844 [==============================] - 5s 7ms/step - loss: 0.0361 - accuracy: 0.9886 - val_loss: 0.0880 - val_accuracy: 0.9743
Epoch 4/5
844/844 [==============================] - 5s 6ms/step - loss: 0.0267 - accuracy: 0.9916 - val_loss: 0.0419 - val_accuracy: 0.9885
Epoch 5/5
157/157 [==============================] - 1s 3ms/step - loss: 0.0650 - accuracy: 0.9810


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, Input, Dense, MaxPool2D, BatchNormalization, Flatten, GlobalAvgPool2D
import matplotlib.pyplot as plt
import numpy as np

# functional approach : function that returns a model (more flexible)
def functional_model():
  my_input = Input(shape=(28,28,1))
  x = Conv2D(32,(3,3),activation='relu')(my_input)
  x = Conv2D(64,(3,3),activation='relu')(x)
  x = MaxPool2D()(x)
  x = BatchNormalization()(x)

  x = Conv2D(128,(3,3), activation='relu')(x)
  x = MaxPool2D()(x)
  x = BatchNormalization()(x)

  x = GlobalAvgPool2D()(x)
  x = Dense(64, activation='relu')(x)
  x = Dense(10, activation='softmax')(x)

  model = tf.keras.Model(inputs=my_input, outputs=x)
  return model

if __name__=='__main__': 
#if I run my script then I want this part here to be rand and 
#if I import it for example I can import my file into another script and tin that case this part will not be called.
#It is a good habit always add this one on my script when I want to separate the behaviors between importing those scripts and running those scripts
  #pass
  (x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data() # import MNIST dataset from keras
  print('x_train.shape=',x_train.shape)
  print('y_train.shape=',y_train.shape)
  print('x_test.shape=',x_test.shape)
  print('y_test.shape=',y_test.shape)
  
  if False:
    display_some_examples(x_train,y_train) # shouw the sample images
  x_train = x_train.astype('float32')/255 # normalisation for not absolutly 0
  x_test = x_test.astype('float32')/255 

  x_train = np.expand_dims(x_train, axis=-1)
  x_test = np.expand_dims(x_test, axis=-1)

  # if we use categorical_crossentropy, we need to use one hot coding
  # label : 2
  # one hot encoding : [0,0,1,0,0,0,0,0,0,0]
  y_train = tf.keras.utils.to_categorical(y_train, 10)
  y_test = tf.keras.utils.to_categorical(y_test, 10)

  model = functional_model()
  model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics='accuracy')

  #model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics='accuracy') # important properties
  
  # model training
  model.fit(x_train, y_train, batch_size=64, epochs=5, validation_split=0.1) # batch size is set the number of imagies to check epoch is trials of whole model

  # train, validation( end of every epoch check not use for train ), test 

  # evaluation on test set
  model.evaluate(x_test, y_test, batch_size=64)

  # Saving bestmodel model

11501568/11490434 [==============================] - 0s 0us/step
x_train.shape= (60000, 28, 28)
y_train.shape= (60000,)
x_test.shape= (10000, 28, 28)
y_test.shape= (10000,)
Epoch 1/5
222/844 [======>.......................] - ETA: 2:08 - loss: 0.5501 - accuracy: 0.8523

KeyboardInterrupt: ignored

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, Input, Dense, MaxPool2D, BatchNormalization, Flatten, GlobalAvgPool2D
import matplotlib.pyplot as plt
import numpy as np

# tensorflow.keras.Model : inherit from this class
class MyCustomModel(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.conv1 = Conv2D(32,(3,3),activation='relu')
    self.conv2 = Conv2D(64,(3,3),activation='relu')
    self.maxpool1 = MaxPool2D()
    self.batchnorm1 = BatchNormalization()

    self.conv3 = Conv2D(128,(3,3), activation='relu')
    self.maxpool2 = MaxPool2D()
    self.batchnorm2 = BatchNormalization()

    self.globalavgpool1 = GlobalAvgPool2D()
    self.dense1 = Dense(64, activation='relu')
    self.dense2 = Dense(10, activation='softmax')

  def call(self, my_input):
    x = self.conv1(my_input)
    x = self.conv2(x)
    x = self.maxpool1(x)
    x = self.batchnorm1(x)
    x = self.conv3(x)
    x = self.maxpool2(x)
    x = self.batchnorm2(x)
    x = self.globalavgpool1(x)
    x = self.dense1(x)
    x = self.dense2(x)

    return x

if __name__=='__main__': 
#if I run my script then I want this part here to be rand and 
#if I import it for example I can import my file into another script and tin that case this part will not be called.
#It is a good habit always add this one on my script when I want to separate the behaviors between importing those scripts and running those scripts
  #pass
  (x_train,y_train),(x_test,y_test) = tf.keras.datasets.mnist.load_data() # import MNIST dataset from keras
  print('x_train.shape=',x_train.shape)
  print('y_train.shape=',y_train.shape)
  print('x_test.shape=',x_test.shape)
  print('y_test.shape=',y_test.shape)
  
  if False:
    display_some_examples(x_train,y_train) # shouw the sample images
  x_train = x_train.astype('float32')/255 # normalisation for not absolutly 0
  x_test = x_test.astype('float32')/255 

  x_train = np.expand_dims(x_train, axis=-1)
  x_test = np.expand_dims(x_test, axis=-1)

  # if we use categorical_crossentropy, we need to use one hot coding
  # label : 2
  # one hot encoding : [0,0,1,0,0,0,0,0,0,0]
  y_train = tf.keras.utils.to_categorical(y_train, 10)
  y_test = tf.keras.utils.to_categorical(y_test, 10)

  model = MyCustomModel()
  model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics='accuracy')

  #model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics='accuracy') # important properties
  
  # model training
  model.fit(x_train, y_train, batch_size=64, epochs=5, validation_split=0.1) # batch size is set the number of imagies to check epoch is trials of whole model

  # train, validation( end of every epoch check not use for train ), test 

  # evaluation on test set
  model.evaluate(x_test, y_test, batch_size=64)

  # Saving bestmodel model

x_train.shape= (60000, 28, 28)
y_train.shape= (60000,)
x_test.shape= (10000, 28, 28)
y_test.shape= (10000,)
Epoch 1/5
844/844 [==============================] - 6s 7ms/step - loss: 0.2150 - accuracy: 0.9414 - val_loss: 0.1215 - val_accuracy: 0.9607
Epoch 2/5
844/844 [==============================] - 5s 6ms/step - loss: 0.0518 - accuracy: 0.9843 - val_loss: 0.0639 - val_accuracy: 0.9795
Epoch 3/5
844/844 [==============================] - 6s 7ms/step - loss: 0.0354 - accuracy: 0.9887 - val_loss: 0.0437 - val_accuracy: 0.9870
Epoch 4/5
844/844 [==============================] - 6s 7ms/step - loss: 0.0268 - accuracy: 0.9916 - val_loss: 0.0572 - val_accuracy: 0.9823
Epoch 5/5
157/157 [==============================] - 1s 3ms/step - loss: 0.0519 - accuracy: 0.9827


In [2]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Conv2D, Input, Dense, MaxPool2D, BatchNormalization, Flatten, GlobalAvgPool2D

def streetsigns_model(nbr_classes):
  my_input = Input(shape=(60,60,3))

  x = Conv2D(32,(3,3),activation='relu')(my_input)
  x = MaxPool2D()(x)
  x = BatchNormalization()(x)

  x = Conv2D(64,(3,3), activation='relu')(x)
  x = MaxPool2D()(x)
  x = BatchNormalization()(x)

  x = Conv2D(128,(3,3), activation='relu')(x)
  x = MaxPool2D()(x)
  x = BatchNormalization()(x)

  #x = Flatten()(x)
  x = GlobalAvgPool2D()(x)
  x = Dense(128, activation='relu')(x)
  x = Dense(nbr_classes, activation='softmax')(x)
  
  return Model(inputs=my_input, outputs=x)

if __name__=='__main__': 
  model = streetsigns_model(10)
  model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 60, 60, 3)]       0         
                                                                 
 conv2d (Conv2D)             (None, 58, 58, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 29, 29, 32)       0         
 )                                                               
                                                                 
 batch_normalization (BatchN  (None, 29, 29, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 27, 27, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 13, 13, 64)       0     

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# German Traffic Sign Recognition Benchmark
import os
import glob
from sklearn.model_selection import train_test_split
import shutil
import csv
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def split_data(path_to_data, path_to_save_train, path_to_save_val, split_size=0.1):
  folders = os.listdir(path_to_data) # all folder direct to folders

  for folder in folders:
    full_path = os.path.join(path_to_data, folder)
    images_paths = glob.glob(os.path.join(full_path,'*.png'))

    x_train, x_val = train_test_split(images_paths, test_size=split_size)

    for x in x_train:
      path_to_folder = os.path.join(path_to_save_train, folder)
      if not os.path.isdir(path_to_folder):
        os.makedirs(path_to_folder)
      
      shutil.copy(x, path_to_folder)
    
    for x in x_val:
      path_to_folder = os.path.join(path_to_save_val, folder)
      if not os.path.isdir(path_to_folder):
        os.makedirs(path_to_folder)
      
      shutil.copy(x, path_to_folder)

def order_test_set(path_to_images, path_to_csv):
  try:
    with open(path_to_csv,'r') as csvfile:
      reader = csv.reader(csvfile, delimiter=',')
      for i, row in enumerate(reader):
        if i==0:
          continue
        img_name = row[-1].replace('Test/', '')
        label = row[-2]

        path_to_folder = os.path.join(path_to_images, label)

        if not os.path.isdir(path_to_folder):
          os.makedirs(path_to_folder)

        img_full_path = os.path.join(path_to_images, img_name)
        shutil.move(img_full_path, path_to_folder)
  except:
    print('[INFO] : Error reading csv file')

def create_generators(batch_size, train_data_path, val_data_path, test_data_path):
  preprocessor = ImageDataGenerator(
      rescale = 1 / 255.
  )

  train_generator = preprocessor.flow_from_directory(
      train_data_path,
      class_mode='categorical',
      target_size=(60,60),
      color_mode='rgb',
      shuffle=True,
      batch_size=batch_size
  )

  val_generator = preprocessor.flow_from_directory(
      val_data_path,
      class_mode='categorical',
      target_size=(60,60),
      color_mode='rgb',
      shuffle=False,
      batch_size=batch_size
  )

  test_generator = preprocessor.flow_from_directory(
      test_data_path,
      class_mode='categorical',
      target_size=(60,60),
      color_mode='rgb',
      shuffle=False,
      batch_size=batch_size
  )

  return train_generator, val_generator, test_generator

In [4]:
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

if __name__=='__main__': 
  if False: #first split datas
    path_to_data = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/Train'
    path_to_save_train = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/train'
    path_to_save_val = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/val'
    split_data(path_to_data, path_to_save_train, path_to_save_val)

  if False: #second split test images
    path_to_images = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/Test'
    path_to_csv = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/Test/csv'
    order_test_set(path_to_images, path_to_csv)

  path_to_train = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/training_data/train'
  path_to_val = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/training_data/val'
  path_to_test = '/content/drive/MyDrive/Colab_Notebooks/GermanTrafficSignRecognitionBenchmark/Test'
  batch_size = 64
  epochs = 15

  train_generator, val_generator, test_generator = create_generators(batch_size, path_to_train, path_to_val, path_to_test)
  nbr_classes = train_generator.num_classes

  path_to_save_model = './Models'
  ckpt_saver = ModelCheckpoint(
      path_to_save_model,
      monitor='val_accuracy',# val_loss
      mode='max', # min
      save_best_only=True,
      save_freq='epoch',
      verbose=1
  )

  early_stop = EarlyStopping(monitor='val_accuracy', patience=10)

  model = streetsigns_model(nbr_classes)

  model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(train_generator,
            epochs=epochs,
            batch_size=batch_size,
            validation_data=val_generator,
            callbacks=[ckpt_saver, early_stop]
            )

Found 26439 images belonging to 43 classes.
Found 3921 images belonging to 43 classes.
Found 2901 images belonging to 13 classes.


NameError: ignored

In [67]:
import numpy as np
pre=7
p=3
class Solution:
    def new21Game(self, n: int, k: int, maxPts: int) -> float:
        win = 0
        for i in range(10**pre*p):
            alice = 0
            while alice < k:
                trial = np.random.randint(maxPts)+1
                alice = alice + trial
            if alice <= n:
                win=win+1
        return win/(10**pre*p)

if __name__ == '__main__':
  print(Solution().new21Game(21,17,10))



0.7327246


In [98]:
class Solution:
    def new21Game(self, n: int, k: int, maxPts: int) -> float:
        if k == 0:
            return 1
        dp = [0 for _ in range(n+maxPts+1)]  
        # we initialize dp[i] to 0 if i > n since it is impossible to reach n >= i >= k starting from i > n
        cur = 0
        
        # iterate in reverse order since we know the probability when n >= i >= k 
        for i in reversed(range(0, n+1)):
            print(i, i+maxPts, k, dp)
            # case when n >= i >= k 
            if i >= k:
                # the probability is 1 since we know it is already in n >= i >= k range and stop drawing
                dp[i] = 1  
            #  case when i < k
            else:
                # (sum of dp[i+1] to dp[i+maxPts]) * (1 / maxPts), where 1 / maxPts is the probability of drawing 1, ..., maxPts
                dp[i] = cur
            # minus the last one and add the previous one to get sum of dp[i+1] to dp[i+maxPts]
            # we can recalculate sum of dp[i+1] to dp[i+maxPts] as well but it is time-consuming
            cur += (dp[i] - dp[i+maxPts]) / maxPts  
            
        return dp[0]


if __name__ == '__main__':
  print(Solution().new21Game(21,17,10))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0
21 31 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
20 30 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
19 29 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
18 28 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
17 27 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
16 26 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
15 25 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
14 24 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0.5, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
13 23 17 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [61]:
i=np.random.randint(10,size=(1000,1000))+1
print(i)
print(i[1])

[[ 2  6  6 ...  4  8  9]
 [ 8  9 10 ...  3 10  3]
 [ 8 10  6 ...  5  8  5]
 ...
 [ 2 10  6 ...  1 10  8]
 [ 4  1  3 ...  5  2  2]
 [ 1  6  6 ...  3  4  5]]
[ 8  9 10  4  5  8  1 10  5  4  5  5  8  4  3  6  1  2  1  6  2  8  5  5
  5  9  3  4 10  9  2  5  2  8  6  7  8  4 10  1  9  2  9  3  5  8  3  7
  7  7  2 10  7  7  4  7  4  8  6  9  5  2  8 10  6  7  8 10 10  4  9  6
  8 10  3  6  4  8  2  3  6 10  4  3  5  9  9  4  8  2  4  4  1  7  1  5
  2  7  8  3  6 10  9  6  8  6  4  1 10  3  3  4  9  4  2  1  4  8  1  8
  4  3  7  2  5 10  8  7  9  6  3  8  3  2  7  5  6  9  9  7  9  9  3  2
  3  2  9  7  7  2  7  4  7  7  7  9  4  3  6  1  1  8  1  7  6  2  7  6
  8  8  5  5  5  7 10  9  9  3  4  9  6  9  5 10  8  6  9  6  4  4  2  5
  3  9  3  2  7  1  3  7  5  9  9  7  3  4  4 10  1  4  8  3  5  4  7  3
  3  1  7  8  3  3  4  8  9  7  5  5 10  5  9  8 10  5  8  4  5  5  2  5
  1  2 10  4  5  3  7  6  8  5  2  1  5  3  6  1  3  2 10 10  6 10  6  1
  4  1  4  7  7  6  7 10 10  2  7 10  5  